server:
   port: 9090

spring:
  application:
    name: realestate-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/auth


  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    '[org.springframework.security]': TRACE
